In [8]:
# Question 10: Designing a Custom Neural Network Layer
# Description: Implement a custom neural network layer from scratch using TensorFlow and integrate it into a model.
import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.metrics import accuracy_score

# Custom Neural Network Layer
class CustomDenseLayer(BaseEstimator, ClassifierMixin):
    def __init__(self, n_units=10, activation='relu'):
        self.n_units = n_units
        self.activation = activation
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        # Initialize weights and biases
        self.weights = np.random.randn(X.shape[1], self.n_units) * 0.01
        self.bias = np.zeros(self.n_units)
        
        # Perform forward pass and calculate output
        self.Z = np.dot(X, self.weights) + self.bias
        if self.activation == 'relu':
            self.A = np.maximum(0, self.Z)
        elif self.activation == 'sigmoid':
            self.A = 1 / (1 + np.exp(-self.Z))
        else:
            raise ValueError("Unsupported activation function")

        return self

    def predict(self, X):
        # Perform the same forward pass for prediction
        Z = np.dot(X, self.weights) + self.bias
        if self.activation == 'relu':
            A = np.maximum(0, Z)
        elif self.activation == 'sigmoid':
            A = 1 / (1 + np.exp(-Z))
        else:
            raise ValueError("Unsupported activation function")
        return A

# Example of using the CustomDenseLayer
if __name__ == "__main__":
    # Sample data
    X = np.random.rand(100, 4)  # 100 samples, 4 features
    y = np.random.randint(0, 2, 100)  # Binary target variable

    # Ensure y is a 1D binary array (flat 1D array)
    y = np.ravel(y)

    # Define the custom neural network model
    model = CustomDenseLayer(n_units=5, activation='sigmoid')

    # Train the model
    model.fit(X, y)

    # Make predictions
    predictions = model.predict(X)

    # Convert predictions to binary values (0 or 1)
    binary_predictions = (predictions > 0.5).astype(int)

    # Ensure both y and binary_predictions are 1D and have the same length
    print("Shape of y:", y.shape)
    print("Shape of binary_predictions:", binary_predictions.shape)

    # Evaluate model accuracy
    print("Model Predictions:\n", binary_predictions)
 






Shape of y: (100,)
Shape of binary_predictions: (100, 5)
Model Predictions:
 [[0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [0 0 0 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 0 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
