Title: Supervised Learning 

Task 1: Identify input-output pairs in a dataset of housing prices.

In [2]:
# Write your code here
import pandas as pd

# Sample dataset
data = {
    'Square Footage': [1500, 2000, 2500, 1800, 2200],
    'Number of Bedrooms': [3, 4, 3, 3, 4],
    'Location': ['Suburban', 'Urban', 'Urban', 'Suburban', 'Suburban'],
    'Age of the House': [10, 5, 8, 15, 7],
    'Price': [300000, 400000, 450000, 350000, 420000]  # Target/output
}

# Create a DataFrame
df = pd.DataFrame(data)

# Identifying input-output pairs
X = df[['Square Footage', 'Number of Bedrooms', 'Location', 'Age of the House']]  # Input features
y = df['Price']  # Target variable

# Output the identified pairs
print("Input Features:")
print(X)
print("\nTarget Output (Price):")
print(y)


Input Features:
   Square Footage  Number of Bedrooms  Location  Age of the House
0            1500                   3  Suburban                10
1            2000                   4     Urban                 5
2            2500                   3     Urban                 8
3            1800                   3  Suburban                15
4            2200                   4  Suburban                 7

Target Output (Price):
0    300000
1    400000
2    450000
3    350000
4    420000
Name: Price, dtype: int64


Task 2: Match labeled images to their correct classifications.

In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
digits = datasets.load_digits()
X = digits.data
y = digits.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a Support Vector Machine model
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.97      1.00      0.99        33
           1       0.97      1.00      0.98        28
           2       1.00      1.00      1.00        33
           3       0.94      0.97      0.96        34
           4       1.00      1.00      1.00        46
           5       0.96      0.96      0.96        47
           6       0.97      0.97      0.97        35
           7       0.97      0.97      0.97        34
           8       1.00      0.93      0.97        30
           9       0.97      0.95      0.96        40

    accuracy                           0.97       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.98      0.97      0.97       360

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  1  0 45  1  0  0  0]
 [ 1  0  0  0  0  0 34  0  0  0]
 [ 0  0  0

Task 3: List potential inputs and outputs for predicting stock prices.

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Example data: Open, High, Low, Volume (features) and Close (target)
X = np.array([[100, 105, 95, 1000],
              [110, 115, 105, 1200],
              [120, 125, 115, 1400],
              [130, 135, 125, 1600],
              [140, 145, 135, 1800]])

y = np.array([105, 115, 125, 135, 145])

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R2 Score: {r2}')


Mean Absolute Error: 0.0
Mean Squared Error: 0.0
R2 Score: 1.0
