Title: Types of Supervised Learning: Regression & Classification


Task 1: Categorize predicting temperatures (regression) vs. identifying animal species in photo(classification).

In [1]:
# Write your code here
from sklearn.datasets import make_regression, load_iris
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# --- Regression Task: Predicting Temperatures ---
X_reg, y_reg = make_regression(n_samples=100, n_features=1, noise=15)
Xr_train, Xr_test, yr_train, yr_test = train_test_split(X_reg, y_reg, test_size=0.2)

reg_model = LinearRegression()
reg_model.fit(Xr_train, yr_train)
reg_predictions = reg_model.predict(Xr_test)

print("Regression Predictions (Temperature):")
print(reg_predictions[:5])

# --- Classification Task: Identifying Species ---
iris = load_iris()
X_cls, y_cls = iris.data, iris.target
Xc_train, Xc_test, yc_train, yc_test = train_test_split(X_cls, y_cls, test_size=0.2)

clf_model = RandomForestClassifier()
clf_model.fit(Xc_train, yc_train)
cls_predictions = clf_model.predict(Xc_test)

print("\nClassification Predictions (Species IDs):")
print(cls_predictions[:5])


Regression Predictions (Temperature):
[-7.74911325  7.13235741  3.16860862  8.2169774   0.08854158]

Classification Predictions (Species IDs):
[2 2 2 0 2]


Task 2: Discuss and decide if predicting GPA based on study hours (regression)

In [2]:
# Write your code here
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Simulated data: study hours vs GPA
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
gpa = np.array([2.0, 2.2, 2.4, 2.6, 2.9, 3.0, 3.2, 3.4, 3.6, 3.8])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(study_hours, gpa, test_size=0.2)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
predictions = model.predict(X_test)

print("Predicted GPA values:")
print(predictions)


Predicted GPA values:
[3.2 2.8]



Task 3: Evaluate whether a model for predicting customer churn is classification or regression.

In [3]:
# Write your code here
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Simulated data: features might include usage, complaints, support calls, etc.
X = np.random.rand(100, 4)  # 100 customers, 4 features
y = np.random.choice([0, 1], size=100)  # 0 = Not Churned, 1 = Churned

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Predict
predictions = model.predict(X_test)

print("Predicted Churn Labels:")
print(predictions)


Predicted Churn Labels:
[1 1 0 1 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1]
